### ISSUE TITLE
what's the method of log-normalized in celldex

### ISSUE THREAD

**Issue by shangguandong1996** [LTLA/celldex#16]
Hi, Dear Developer
I noticed that according to the celldex manual, the value of celldex is log-norm or something like TPM. 
> Each dataset contains a log-normalized expression matrix that is intended to be comparable to log-UMI counts from common single-cell protocols (Aran et al. 2019) or gene length-adjusted values from bulk datasets.

But I am wondering whehter you can tell me what's the methods behind the log-norm count. Because I also want to make a similar database but for Arabidopsis thaliana

Best wishes

Guandong Shang

**Comment by j-andrews7** [comment]
The expression values vary between datasets. Many of them were simple `log2(counts +1)` transformations, some were pulled from databases that provided them in a log-transformed scale. You can see the various scripts that were used to download and process the data [here](https://github.com/LTLA/celldex/tree/master/inst/scripts).

Regardless, to make your own, a simple log2 transformation of raw counts is likely appropriate.
