### ISSUE TITLE
HumanPrimaryCellAtlasDAta() - invalid class "SummarizedExperiment" object

### ISSUE THREAD

**Issue by LineS97** [LTLA/celldex#17]
Hi!

Today, I experienced this issue:
<img width="544" alt="image" src="https://user-images.githubusercontent.com/61935493/192724772-c496538d-fcc6-49cb-b353-c09814568c8b.png">

I have been following the vignette: https://rdrr.io/github/LTLA/celldex/f/vignettes/userguide.Rmd

library(celldex)
ref <- HumanPrimaryCellAtlasData()

I get the following error:
snapshotDate(): 2022-04-26
see ?celldex and browseVignettes('celldex') for documentation
loading from cache
see ?celldex and browseVignettes('celldex') for documentation
loading from cache
Error in validObject(.Object) : 
  invalid class “SummarizedExperiment” object: 
    nb of cols in 'assay' (2) must equal nb of rows in 'colData' (713)

Versions:
 celldex_1.6.0
SummarizedExperiment_1.26.1
R version 4.2.0

**Comment by LTLA** [comment]
I think your cache is corrupted. Perhaps you can try forcing an update with:

```r
ExperimentHub::ExperimentHub()[["EH3492", force=TRUE]]
```

And then running `HumanPrimaryCellAtlasData()` again.

**Comment by LineS97** [comment]
It solved my problem! Thank you!

**Comment by gadepallivs** [comment]
I'm trying to automatically add cell indents for https://www.heartcellatlas.org/. If I use,  HumanPrimaryCellAtlasData() , get too many indents assigned and overlap. How to filter uses only relevant heart cells ?
