### ISSUE TITLE
Difference between label.main and label.fine?

### ISSUE THREAD

**Issue by bl24** [LTLA/celldex#18]
Hi, I used the MouseRNAseqData reference data to annotate the same data twice, once using the label.main annotation and once using the label.fine. I'm wondering how do I end up with clusters being labeled differently. For instance, the cluster that is labeled Erythrocytes changes depending on which annotation level I use. 

![Cell_clusters_annotated_v2](https://user-images.githubusercontent.com/14930703/198393523-884b5c41-34a6-48db-9774-4ce3fa6f155a.png)
![Cell_clusters_annotated_v3](https://user-images.githubusercontent.com/14930703/198393622-57b8d966-3ef9-4f3f-bcdf-f08452255452.png)

**Comment by LTLA** [comment]
The fine labels are nested within the main labels, the former are just more finely resolved.

```r
> table(X$label.fine, X$label.main)[,"Erythrocytes"]
           Adipocytes                 aNSCs            Astrocytes
                    0                     0                     0
 Astrocytes activated               B cells        Cardiomyocytes
                    0                     0                     0
      Dendritic cells     Endothelial cells             Ependymal
                    0                     0                     0
         Erythrocytes           Fibroblasts Fibroblasts activated
                    3                     0                     0
Fibroblasts senescent          Granulocytes           Hepatocytes
                    0                     0                     0
          Macrophages Macrophages activated             Microglia
                    0                     0                     0
  Microglia activated             Monocytes               Neurons
                    0                     0                     0
    Neurons activated              NK cells                  NPCs
                    0                     0                     0
     Oligodendrocytes                  OPCs                 qNSCs
                    0                     0                     0
              T cells
                    0
```

I don't know what's going on in the above plot, though. Kind of wild to see erythrocytes and neurons getting mixed up. I assume you're using **SingleR**, so you might want to look at what markers are being used to identify each cell type.

**Comment by bl24** [comment]
That's correct. I used SingleR.
