### ISSUE TITLE
Could not install celldex

### ISSUE THREAD

**Issue by GangLiTarheel** [LTLA/celldex#3]
Hi, I am trying to install this package to go through the tutorials in singleR package. But I met the following error. I am using R 4.0.1. Is there any other package I need to install before I install celldex? Please advise! Thanks ahead! Best, Gang

> BiocManager::install("celldex")
Bioconductor version 3.11 (BiocManager 1.30.10), R 4.0.1 (2020-06-06)
Installing package(s) 'celldex'
Warning message:
package ‘celldex’ is not available (for R version 4.0.1)

**Comment by LTLA** [comment]
You need Bioconductor 3.12, as described [here](http://bioconductor.org/packages/3.12/data/experiment/html/celldex.html).
