### ISSUE TITLE
need your help

### ISSUE THREAD

**Issue by adistman** [LTLA/celldex#4]
Thanks for your help! Yesterday, I install this package, and I use it ,but when I do what your sample show me to do. the error is as following:
"> ref.se <- HumanPrimaryCellAtlasData()
  |===========================================================================================| 100%

snapshotDate(): 2020-04-27
Error in .local(x, i, j = j, ...) : 'i' must be length 1"

**Comment by LTLA** [comment]
The error message should have more content than that; I would suggest showing it. But I can already guess what your problem is. **celldex** is available on BioC 3.12 and you are probably using 3.11, based on the ExperimentHub snapshot date.

**Comment by adistman** [comment]
Thank for your help, I know the problem, and solve it ,I libraray(singleR) AND (celldex) at the same time, so they are paradox with each other, and when I closed the celldex, just use the singleR, there is no such problem
