### ISSUE TITLE
cannot find celldex R package

### ISSUE THREAD

**Issue by liuweihanty** [LTLA/celldex#5]
Dear creaters of celldex,

When I am installing celldex using
**if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install(celldex)**
The folloing error message appeared:
Bioconductor version 3.11 (BiocManager 1.30.10), R 4.0.2 (2020-06-22)
**Installing package(s) 'cell*'
package ‘cell*’ is not available (for R version 4.0.2)cannot open URL 'https://bioconductor.org/packages/3.11/data/annotation/bin/macosx/contrib/4.0/PACKAGES.rds': HTTP status was '404 Not Found'**

and when I search available packages starting with "celld" using **BiocManager::available("celld*")**, celldex didn't appear in the list:
![Screenshot 2021-02-22 at 08 49 28](https://user-images.githubusercontent.com/43444815/108724388-e189b600-74ea-11eb-8bbe-22afff089810.png)

Do you know what might be the issue here? Thank you so much!

**Comment by liuweihanty** [comment]
ah nvm, I resolved the issue using:

install.packages("remotes")
remotes::install_github("LTLA/celldex")

thanks!

**Comment by LTLA** [comment]
**celldex** is only available in BioC 3.12 or higher, for R 4.0.0 or higher. If you install it on an older version, there's no guarantee that it'll work properly.

**Comment by liuweihanty** [comment]
I see thank you! I updated my BioC and was able to run smoothly

**Comment by joyalmathew9** [comment]
I am using BioC version 3.18 and R version 4.3.0 but I am not able to install celldex. I am getting the following error:
Error: package 'matrixStats' 0.63.0 was found, but >= 1.0.0 is required by 'MatrixGenerics'
In addition: Warning messages:
1: package 'SummarizedExperiment' was built under R version 4.3.1 
2: package 'MatrixGenerics' was built under R version 4.3.1 
Execution halted
ERROR: lazy loading failed for package 'celldex'

I tried installing matrcistats version BiocManager::install("matrixStats", version = "1.0.0")
But not working. Can someone please help me fix this issue and install celldex
Thank you

**Comment by joyalmathew9** [comment]
It was an issue with my R version and it's resolved. 

Thanks.
