### ISSUE TITLE
Error: failed to load  resource (but HumanPrimaryCellAtlasData is working)

### ISSUE THREAD

**Issue by hypaik** [LTLA/celldex#6]
Hi, developer of celldex

I've installed celldex (BiocManager 3.12 and R version 4.0.xx)to use SingleR.

However, I can only load HumanPrimaryCellAtlasData. Other ref data like BluepringEncodeData, MonacoImmuneData, DatabaseImmuneCellExpressionData are failed to load resource.

Here is the error message I got.

> library('SingleR') #dont use same with cell dex
> library('celldex')
> library('Seurat')
> hpca.se<-HumanPrimaryCellAtlasData()
snapshotDate(): 2021-03-04
see ?celldex and browseVignettes('celldex') for documentation
loading from cache
see ?celldex and browseVignettes('celldex') for documentation
loading from cache
> enco.bl <-BlueprintEncodeData(ensembl = TRUE) #fail load
snapshotDate(): 2021-03-04
see ?celldex and browseVignettes('celldex') for documentation
loading from cache
Error: failed to load resource
  name: EH3486
  title: Blueprint/Encode RNA-seq logcounts
  reason: unknown input format
> enco.bl <-BlueprintEncodeData() 
snapshotDate(): 2021-03-04
see ?celldex and browseVignettes('celldex') for documentation
loading from cache
Error: failed to load resource
  name: EH3486
  title: Blueprint/Encode RNA-seq logcounts
  reason: unknown input format
> monaco <-MonacoImmuneData() #fail load
snapshotDate(): 2021-03-04
see ?celldex and browseVignettes('celldex') for documentation
loading from cache
Error: failed to load resource
  name: EH3496
  title: Monaco Immune Cell RNA-seq logcounts
  reason: unknown input format
> himmune<-DatabaseImmuneCellExpressionData()
snapshotDate(): 2021-03-04
see ?celldex and browseVignettes('celldex') for documentation
loading from cache
Error: failed to load resource
  name: EH3488
  title: DICE RNA-seq logcounts
  reason: unknown input format
> hpca.se
class: SummarizedExperiment 
dim: 19363 713 
metadata(0):
assays(1): logcounts
rownames(19363): A1BG A1BG-AS1 ... ZZEF1 ZZZ3
rowData names(0):
colnames(713): GSM112490 GSM112491 ... GSM92233 GSM92234
colData names(3): label.main label.fine label.ont
> enco.bl
Error: object 'enco.bl' not found
> monaco
Error: object 'monaco' not found
> himmune
Error: object 'himmune' not found

**Comment by LTLA** [comment]
Works fine for me. I note that your snapshot date indicates that you're somehow connecting to the devel version of ExperimentHub; my snapshot date on BioC-release (3.12) is `2020-10-27`, while the snapshot date on BioC-devel (3.13) is `2021-03-04`.

You should probably try to figure out what's going on there; seems like you're mixing BioC-devel and -release packages.

**Comment by hypaik** [comment]
Thank you for your prompt response.
I removed the package of ExperimentHub, then re-install using BioC-release(3.12).
But the problems are repeated.

Here are the code and errors.

if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
BiocManager::install(version = "3.12")
BiocManager::install("celldex")
BiocManager::install("SingleR")
BiocManager::install("scRNAseq")

library('SingleR') 
library('celldex')

> hpca.se<-HumanPrimaryCellAtlasData()
snapshotDate(): 2020-10-27
see ?celldex and browseVignettes('celldex') for documentation
loading from cache
see ?celldex and browseVignettes('celldex') for documentation
loading from cache
> enco.bl <-BlueprintEncodeData()
snapshotDate(): 2020-10-27
see ?celldex and browseVignettes('celldex') for documentation
loading from cache
Error: failed to load resource
  name: EH3486
  title: Blueprint/Encode RNA-seq logcounts
  reason: unknown input format
> monaco <-MonacoImmuneData() #fail load
snapshotDate(): 2020-10-27
see ?celldex and browseVignettes('celldex') for documentation
loading from cache
Error: failed to load resource
  name: EH3496
  title: Monaco Immune Cell RNA-seq logcounts
  reason: unknown input format
> himmune<-DatabaseImmuneCellExpressionData()
snapshotDate(): 2020-10-27
see ?celldex and browseVignettes('celldex') for documentation
loading from cache
Error: failed to load resource
  name: EH3488
  title: DICE RNA-seq logcounts
  reason: unknown input format

**Comment by LTLA** [comment]
1. Show your `sessionInfo()`.
2. Fix any problems raised by `BiocManager::valid()`.

**Comment by hypaik** [comment]
In addition, I also tried the same code with another lab member using her computer (Window system). She also failed. She can't load any data from HumanPrimaryCellAtlasData(), BlueprintEncodeData(), and MonacoImmuneData().

**Comment by LTLA** [comment]
¯\\\_(ツ)\_/¯

I have no idea why. I've never seen this error before. Best guess is that the RDS file is corrupted or the wrong file was downloaded somehow, I'm assuming that the error is being thrown from `readRDS()` (see [here](https://stackoverflow.com/questions/6473831/readrdsfile-in-r)). 

I don't know why this would happen, but you may have to destroy your cache directory and redownload the files.

```r
library(Experiment)
hubCache(ExperimentHub()) # delete this path
```

Perhaps @lshep may have seen this before.

**Comment by hypaik** [comment]
Dear Aaron

I already tried (removing caches), sigh...
Now, cell dex can't load anything. All of the Cache files in the hubCache directory are too small. (just 640B)
As you mentioned, I agree that something wrong happened in ExperimentHub.

So, I tested the following code. And I found that ExperimentHub doesn't work. 

> library('celldex')
> hpca.se<-celldex::HumanPrimaryCellAtlasData() #OK
~/Library/Caches/ExperimentHub
  does not exist, create directory? (yes/no): yes
  |                                                                                                                                                                                                                         |                                                                                                                                                                                                                 |   0%  |                                                                                                                                                                                                                         |=                                                                                                                                                                                                                |   0%  |                                                                                                                                                                                                                         |=                                                                                                                                                                                                                |   1%  |l-===
snapshotDate(): 2020-10-27
see ?celldex and browseVignettes('celldex') for documentation
downloading 1 resources
retrieving 1 resource
Downloading: 640 B     Downloading: 640 B     Downloading: 640 B     Downloading: 640 B     Downloading: 640 B     Downloading: 640 B     
loading from cache
Error: failed to load resource
  name: EH3492
  title: Human Primary Cell Atlas logcounts
  reason: unknown input format
> enco.bl <-celldex::BlueprintEncodeData() #fail load
snapshotDate(): 2020-10-27
see ?celldex and browseVignettes('celldex') for documentation
downloading 1 resources
retrieving 1 resource
Downloading: 640 B     Downloading: 640 B     Downloading: 640 B     Downloading: 640 B     Downloading: 640 B     Downloading: 640 B     
loading from cache
Error: failed to load resource
  name: EH3486
  title: Blueprint/Encode RNA-seq logcounts
  reason: unknown input format
> monaco <-celldex::MonacoImmuneData() #fail load
snapshotDate(): 2020-10-27
see ?celldex and browseVignettes('celldex') for documentation
downloading 1 resources
retrieving 1 resource
Downloading: 640 B     Downloading: 640 B     Downloading: 640 B     Downloading: 640 B     Downloading: 640 B     Downloading: 640 B     
loading from cache
Error: failed to load resource
  name: EH3496
  title: Monaco Immune Cell RNA-seq logcounts
  reason: unknown input format
> himmune<-celldex::DatabaseImmuneCellExpressionData() #fail load
snapshotDate(): 2020-10-27
see ?celldex and browseVignettes('celldex') for documentation
downloading 1 resources
retrieving 1 resource
Downloading: 640 B     Downloading: 640 B     Downloading: 640 B     Downloading: 640 B     Downloading: 640 B     Downloading: 640 B     
loading from cache
Error: failed to load resource
  name: EH3488
  title: DICE RNA-seq logcounts
  reason: unknown input format

> library(ExperimentHub)
Loading required package: AnnotationHub
Loading required package: BiocFileCache
Loading required package: dbplyr

Attaching package: ‘AnnotationHub’

The following object is masked from ‘package:Biobase’:

    cache

> eh=ExperimentHub()
snapshotDate(): 2020-10-27
> query(eh, "EH3492")
ExperimentHub with 0 records
# snapshotDate(): 2020-10-27
> query(eh, "EH1")
ExperimentHub with 0 records
# snapshotDate(): 2020-10-27
> myfiles <- query(eh, "PACKAGENAME")
> myfiles[[1]]
Error in .local(x, i, j = j, ...) : 'i' must be length 1
> myfiles
ExperimentHub with 0 records
# snapshotDate(): 2020-10-27

**Comment by LTLA** [comment]
I'll bet that those 640 bytes contain an error message with the real problem.

**Comment by hypaik** [comment]
Dear developer.

I tried another lab member's computer, and he can load the resource without any problem.
This morning, I tried other methods, then I can load the resource.
Here, is the method I've used.

Delete celldex, SingleR, and reinstall everything.
Destroy the directory of Experiment Hub Caches.
Deleted *.RData, *.Rhistory files. And use a different working directory.
Switch off the ethernet cable and activate the wifi connection of my computer. (My institute blocked AWS for security.)
celldex worked properly.
So, I think this issue associated with the firewall of my institute.
However, it's still unclear how another lab member can load the resource via ethernet cable.
I think I can figure it out with the IT administrator of my institute.

Now I have a quick question. Do I need to save the downloaded resource as an RData?
Because the Wifi setting is slow in my institute, it seems uncomfortable to use wifi for every analysis.

**Comment by LTLA** [comment]
> My institute blocked AWS for security.

I daresay this is the biggest problem. The reinstallations won't have any effect. The deletion of the RData/Rhistory is highly unlikely to have an effect. The deletion of the caches only has an effect with respect to getting rid of the weird 640 byte downloads that have contaminated your existing cache. 

I can't comprehend why your institute thinks that blocking read access to AWS is a sensible thing to do. (ENCODE hosts all of their datasets on S3, for example.) That's a big world of data that's being blocked.

> Now I have a quick question. Do I need to save the downloaded resource as an RData?

No. Once successfully downloaded, files are automatically cached. You won't have to download them again.

**Comment by hypaik** [comment]
Thank you for your response.

I totally agree that blocking AWS is the big issue. There are several ways to bypass the firewall.
Based on your answer, I would not save the data as RData. 

So, my problem is solved. I would close this issue.

Regards,
HP
