### ISSUE TITLE
error when trying to get ref data

### ISSUE THREAD

**Issue by christoforos-dimitropoulos** [LTLA/celldex#8]
Hey

I am getting the following error when I run the ImmGenData function

```
 immgen <- ImmGenData(ensembl=TRUE)
Error: 'R_user_dir' is not an exported object from 'namespace:tools'
```

Is there a way to deal with it?
Thanks

**Comment by LTLA** [comment]
You'll need R 4.0 or higher. You shouldn't have been able to install the latest version of BioC packages without it.
